server:
  port: 8761

spring:
  application:
    name: "Service registry"
  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    enabled: true
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  registration:
    enabled: false

